# Generated by Django 3.2.9 on 2022-04-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_update_help_text_replace_float_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-release_date', '-date_created')},
        ),
    ]
