# Generated by Django 3.2.16 on 2023-01-23 16:04

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_auto_20220923_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='logo',
            field=models.FileField(help_text='A PNG picture with transparency, featuring the logo.', upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_header',
            field=models.FileField(help_text='A 1920x850 header image. No text.', upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.FileField(help_text='A 1508x2133 poster for the film.', upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='film',
            name='thumbnail',
            field=models.FileField(help_text='A 1920x1080 image for social media preview.', upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
