# Generated by Django 3.2.16 on 2023-09-05 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'On Hold'), ('expired', 'Expired')], default='active', max_length=200)),
                ('plan', models.IntegerField(choices=[(30, '1 Month'), (90, '3 Month'), (180, '6 Month'), (365, '1 Year')])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playment_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=200)),
                ('plan', models.IntegerField(choices=[(30, '1 Month'), (90, '3 Month'), (180, '6 Month'), (365, '1 Year')])),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('alipay', 'Alipay'), ('wechat_pay', 'Wechat Pay'), ('other', 'Other')], default='other', max_length=200)),
                ('payment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True)),
                ('payment_intent', models.CharField(blank=True, max_length=200)),
                ('user_email', models.CharField(blank=True, max_length=200)),
                ('receipt_url', models.CharField(blank=True, max_length=255)),
                ('order_time', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_playment_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
