[tool.poetry]
name = "blender-studio"
version = "0.1.0"
description = ""
authors = ["Sem Mulder <sem@blender.studio>"]

[tool.poetry.dependencies]
python = "^3.8.1"
Django = "^3.0"
django-pipeline = "^1.7"
psycopg2 = "^2.8"
blender_id_oauth_client = {path = "../blender-id-oauth-client"}
Jinja2 = "^2.11.1"
libsasscompiler = "^0.1.5"
jsmin = "^2.2.2"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
mypy = "*"
django-stubs = "*"

[tool.black]
line-length = 100
target_version = ['py38']
skip_string_normalization = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
