# Generated by Django 3.2.16 on 2022-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_auto_20220923_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactershowcase',
            name='min_blender_version',
            field=models.CharField(choices=[('2.70', 'V270'), ('2.80', 'V280'), ('2.90', 'V290'), ('3.0', 'V300'), ('3.1', 'V310'), ('3.4', 'V340')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='characterversion',
            name='min_blender_version',
            field=models.CharField(choices=[('2.70', 'V270'), ('2.80', 'V280'), ('2.90', 'V290'), ('3.0', 'V300'), ('3.1', 'V310'), ('3.4', 'V340')], db_index=True, max_length=5),
        ),
    ]
