---
- name: Copying MaxMind DB
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ dir.source }}"
    owner: "{{ nginx.user }}"
    group: "{{ group }}"
    mode: u+rw,g+r
  with_community.general.filetree: "{{ maxminddb_download_path }}"
  when: '"GeoLite2-Country.mmdb" in item.get("src", "")'
  tags:
    - maxminddb
