# Generated by Django 3.2.16 on 2023-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_staticassetcountedvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticassetdownload',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staticassetview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunSQL(
            "UPDATE stats_staticassetdownload SET date_created = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE stats_staticassetview SET date_created = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
