# Generated by Django 3.2.16 on 2023-01-23 16:04

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.FileField(blank=True, help_text='A 2048x640 picture for the blog header. Can be abstract.', upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='A 1920x1080 picture for the blog list and on social media.', upload_to=common.upload_paths.get_upload_to_hashed_path),
        ),
    ]
