# Generated by Django 3.2.9 on 2022-02-10 15:24

from django.db import migrations, models
import django.db.models.deletion
import static_assets.models.static_assets


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0011_add_static_asset_view_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='license',
            field=models.ForeignKey(blank=True, default=static_assets.models.static_assets._get_default_license_id, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='static_assets', to='static_assets.license'),
        ),
    ]
