# Generated by Django 3.2.16 on 2023-08-28 09:59

from django.db import migrations, models
import django.db.models.deletion
import static_assets.models.m3u8_assets


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0012_allow_blank_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='M3U8Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('types', models.CharField(choices=[('playlist', 'Playlist'), ('video', 'Video'), ('audio', 'Audio')], max_length=200)),
                ('source', models.FileField(blank=True, max_length=255, null=True, upload_to=static_assets.models.m3u8_assets.SourcePATH)),
                ('sVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M3U8Video', to='static_assets.staticasset')),
            ],
        ),
    ]
