# Generated by Django 3.2.16 on 2023-09-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0015_auto_20230831_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m3u8playlist',
            name='sVideo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='M3U8Video', to='static_assets.staticasset'),
        ),
    ]
