# Generated by Django 3.2.16 on 2023-09-13 02:24

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0016_alter_m3u8playlist_svideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='m3u8playlist',
            name='slug',
            field=models.SlugField(default=common.upload_paths.shortuid),
        ),
    ]
