# Generated by Django 3.2.16 on 2023-09-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0017_m3u8playlist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m3u8source',
            name='m3u8_Playlist',
        ),
        migrations.AlterField(
            model_name='m3u8source',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M3U8Source', to='static_assets.m3u8playlist'),
        ),
    ]
