# Generated by Django 3.2.16 on 2023-09-15 09:57

import common.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0018_auto_20230913_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='slug',
            field=models.SlugField(blank=True, default=common.upload_paths.shortuid),
        ),
    ]
