# Generated by Django 3.2.16 on 2023-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_assets', '0019_alter_staticasset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticasset',
            name='original_filename',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
