# Generated by Django 3.2.9 on 2022-01-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_update_help_text_replace_float_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='difficulty',
            field=models.TextField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')]),
        ),
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.TextField(choices=[('workshop', 'Workshop'), ('course', 'Course'), ('documentation', 'Documentation')]),
        ),
    ]
